from __future__ import annotations

import logging
import os
import sys

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.config import (  # noqa: E402
    API_PREFIX,
    APP_TITLE,
    APP_VERSION,
    DEFAULT_BACKEND_HOST,
    DEFAULT_BACKEND_PORT,
    DEFAULT_WEIGHTS_PATH,
    FRONTEND_DIR,
)
from backend.routes.api_v2 import router  # noqa: E402
from backend.services import prediction_service  # noqa: E402
from database.db import close_db  # noqa: E402

load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger("eyenet")

app = FastAPI(
    title=APP_TITLE,
    version=APP_VERSION,
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix=API_PREFIX)

if FRONTEND_DIR.is_dir():
    # Production: Serve the 'dist' folder generated by 'npm run build'
    static_root = FRONTEND_DIR / "dist"
    if not static_root.is_dir():
        static_root = FRONTEND_DIR

    # Mount assets folder first so it takes precedence for nested files
    assets_dir = static_root / "assets"
    if assets_dir.is_dir():
        app.mount("/assets", StaticFiles(directory=str(assets_dir)), name="assets")
    
    # Mount everything else in static root (imgs, icons, etc)
    app.mount("/static", StaticFiles(directory=str(static_root)), name="static")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_frontend(full_path: str):
        # Prevent shadowing API routes
        if full_path.startswith("api/") or full_path.startswith("docs") or full_path.startswith("redoc"):
            return None
            
        file_path = static_root / full_path
        if file_path.is_file():
            return FileResponse(file_path)
        
        # Fallback to index.html for SPA routing (React)
        return FileResponse(static_root / "index.html")


@app.on_event("startup")
async def startup_event():
    weights_path = os.getenv("MODEL_WEIGHTS_PATH", str(DEFAULT_WEIGHTS_PATH))
    device = "cuda" if os.getenv("USE_GPU", "0") == "1" else "cpu"
    prediction_service.load_model(weights_path=weights_path, device_str=device)
    logger.info("EyeNet backend ready at /docs")


@app.on_event("shutdown")
async def shutdown_event():
    close_db()
    logger.info("EyeNet backend stopped")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "backend.app_server:app",
        host=os.getenv("BACKEND_HOST", DEFAULT_BACKEND_HOST),
        port=int(os.getenv("BACKEND_PORT", DEFAULT_BACKEND_PORT)),
        reload=True,
    )
